
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あわ　あわもち', 5.1, 1.3, 45.3, 210);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えんばく　オートミール', 13.7, 5.7, 69.1, 350);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おおむぎ　七分つき押麦', 10.9, 2.1, 72.1, 343);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おおむぎ　押麦　乾', 6.7, 1.5, 78.3, 329);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おおむぎ　押麦　めし', 2.2, 0.5, 28.5, 118);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おおむぎ　米粒麦', 7.0, 2.1, 76.2, 333);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おおむぎ　大麦めん　乾', 12.9, 1.7, 68.0, 343);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おおむぎ　大麦めん　ゆで', 4.8, 0.6, 24.3, 121);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おおむぎ　麦こがし', 12.5, 5.0, 77.1, 368);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('キヌア　玄穀', 13.4, 3.2, 69.0, 344);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('きび　精白粒', 11.3, 3.3, 70.9, 353);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［玄穀］　国産　普通', 10.8, 3.1, 72.1, 329);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［玄穀］　輸入　軟質', 10.1, 3.3, 75.2, 344);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［玄穀］　輸入　硬質', 13.0, 3.0, 69.4, 332);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　薄力粉　1等', 8.3, 1.5, 75.8, 349);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　薄力粉　2等', 9.3, 1.9, 74.3, 345);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　中力粉　1等', 9.0, 1.6, 75.1, 337);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　中力粉　2等', 9.7, 1.8, 74.0, 346);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　強力粉　1等', 11.8, 1.5, 71.7, 337);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　強力粉　2等', 12.6, 1.7, 70.6, 343);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　強力粉　全粒粉', 12.8, 2.9, 68.2, 320);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　プレミックス粉　お好み焼き用', 10.1, 1.9, 73.6, 335);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　プレミックス粉　ホットケーキ用', 7.8, 4.0, 74.4, 360);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　プレミックス粉　から揚げ用', 10.2, 1.2, 70.0, 311);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　プレミックス粉　天ぷら用', 8.8, 1.3, 76.1, 337);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　プレミックス粉　天ぷら用　バッター', 3.3, 0.5, 30.2, 132);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［小麦粉］　プレミックス粉　天ぷら用　バッター　揚げ', 4.3, 47.7, 37.0, 588);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　角形食パン　食パン', 8.9, 4.1, 46.4, 248);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　角形食パン　焼き', 9.7, 4.5, 50.6, 269);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　角形食パン　耳を除いたもの', 8.2, 3.7, 42.6, 226);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　角形食パン　耳', (9.7), (4.5), (50.8), 273);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　食パン　リーンタイプ', (8.0), (3.7), (47.5), 246);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　食パン　リッチタイプ', (7.8), (6.0), (45.6), 256);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　山形食パン　食パン', (7.8), (3.5), (47.9), 246);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　コッペパン', 9.2, 3.8, 54.7, 273);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　バンズ', 10.4, 4.8, 50.6, 274);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　乾パン', 9.5, 4.4, 78.8, 386);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　フランスパン', 9.4, 1.3, 57.5, 289);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　ライ麦パン', 8.4, 2.2, 52.7, 252);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　全粒粉パン', 7.9, 5.7, 45.5, 251);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　ぶどうパン', 8.2, 3.5, 51.1, 263);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　ロールパン', 10.1, 9.0, 48.6, 309);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　クロワッサン　レギュラータイプ', (6.5), (20.4), (51.5), 406);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　クロワッサン　リッチタイプ', 7.9, 26.8, 43.9, 438);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　くるみパン', (8.2), (12.6), (38.7), 292);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　イングリッシュマフィン', 8.1, 3.6, 40.8, 224);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　ナン', 10.3, 3.4, 47.6, 257);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［パン類］　ベーグル', 9.6, 2.0, 54.6, 270);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［うどん・そうめん類］　うどん　生', 6.1, 0.6, 56.8, 249);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［うどん・そうめん類］　うどん　ゆで', 2.6, 0.4, 21.6, 95);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［うどん・そうめん類］　うどん　半生うどん', (7.8), (3.4), (62.5), 296);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［うどん・そうめん類］　干しうどん　乾', 8.5, 1.1, 71.9, 333);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［うどん・そうめん類］　干しうどん　ゆで', 3.1, 0.5, 25.8, 117);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［うどん・そうめん類］　そうめん・ひやむぎ　乾', 9.5, 1.1, 72.7, 333);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［うどん・そうめん類］　そうめん・ひやむぎ　ゆで', 3.5, 0.4, 25.8, 114);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［うどん・そうめん類］　手延そうめん・手延ひやむぎ　乾', 9.3, 1.5, 68.9, 312);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［うどん・そうめん類］　手延そうめん・手延ひやむぎ　ゆで', 3.5, 0.6, 25.5, 119);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［中華めん類］　中華めん　生', 8.6, 1.2, 55.7, 249);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［中華めん類］　中華めん　ゆで', 4.9, 0.6, 29.2, 133);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［中華めん類］　半生中華めん　', (9.9), (4.0), (61.2), 305);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［中華めん類］　蒸し中華めん　蒸し中華めん', 4.9, 1.7, 35.6, 162);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［中華めん類］　蒸し中華めん  ソテー', 5.2, 4.9, 38.9, 211);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［中華めん類］　干し中華めん　乾', 11.7, 1.6, 70.2, 337);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［中華めん類］　干し中華めん　ゆで', 4.9, 0.5, 27.5, 131);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［中華めん類］　沖縄そば　生', 9.2, 2.0, 54.2, 266);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［中華めん類］　沖縄そば　ゆで', 5.2, 0.8, 28.0, 132);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［中華めん類］　干し沖縄そば　乾', 12.0, 1.7, 67.8, 317);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［中華めん類］　干し沖縄そば　ゆで', 5.2, 0.6, 28.6, 132);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　即席中華めん　油揚げ味付け', 10.1, 16.7, 63.5, 424);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　即席中華めん　油揚げ　乾　（添付調味料等を含むもの）', 10.1, 19.1, 61.4, 439);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　即席中華めん　油揚げ　調理後全体　（添付調味料等を含むもの）', (2.3), (4.4), (13.4), 100);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　即席中華めん　油揚げ　ゆで　（添付調味料等を含まないもの）', 3.9, 7.7, 27.9, 189);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　即席中華めん　油揚げ　乾　（添付調味料等を含まないもの）', 8.9, 19.6, 65.5, 453);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　即席中華めん　非油揚げ　乾　（添付調味料等を含むもの）', 10.3, 5.2, 67.1, 336);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　即席中華めん　非油揚げ　調理後全体　（添付調味料等を含むもの）', (3.0), (0.8), (18.7), 93);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　即席中華めん　非油揚げ　ゆで　（添付調味料等を含まないもの）', 3.4, 0.8, 31.0, 139);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　即席中華めん　非油揚げ　乾　（添付調味料等を含まないもの）', 8.5, 1.9, 75.2, 334);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　中華スタイル即席カップめん　油揚げ　塩味　乾　（添付調味料等を含むもの）', 10.9, 18.5, 58.6, 422);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　中華スタイル即席カップめん　油揚げ　塩味　調理後全体　（添付調味料等を含むもの）', (2.5), (4.2), (13.2), 92);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　中華スタイル即席カップめん　油揚げ　塩味　調理後のめん　（スープを残したもの）', 3.8, 7.7, 25.2, 175);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　中華スタイル即席カップめん　油揚げ　しょうゆ味　乾　（添付調味料等を含むもの）', 10.0, 19.1, 54.6, 417);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　中華スタイル即席カップめん　油揚げ　しょうゆ味　調理後全体　（添付調味料等を含むもの）', (2.3), (4.5), (12.9), 90);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　中華スタイル即席カップめん　油揚げ　しょうゆ味　調理後のめん　（スープを残したもの）', 3.0, 5.8, 20.7, 142);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　中華スタイル即席カップめん　油揚げ　焼きそば　乾　（添付調味料等を含むもの）', 8.2, 18.6, 57.5, 418);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　中華スタイル即席カップめん　油揚げ　焼きそば　調理後全体　（添付調味料等を含むもの）', (5.0), (11.3), (34.2), 222);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　中華スタイル即席カップめん　非油揚げ　乾　（添付調味料等を含むもの）', 9.2, 5.8, 62.6, 314);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　中華スタイル即席カップめん　非油揚げ　調理後全体　（添付調味料等を含むもの）', (2.5), (2.1), (10.2), 66);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　中華スタイル即席カップめん　非油揚げ　調理後のめん　（スープを残したもの）', 3.4, 1.3, 25.3, 121);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　和風スタイル即席カップめん　油揚げ　乾　（添付調味料等を含むもの）', 10.9, 19.8, 56.1, 437);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　和風スタイル即席カップめん　油揚げ　調理後全体　（添付調味料等を含むもの）', (2.2), (4.7), (11.2), 91);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［即席めん類］　和風スタイル即席カップめん　油揚げ　調理後のめん　（スープを残したもの）', 2.7, 7.2, 24.4, 163);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［マカロニ・スパゲッティ類］　マカロニ・スパゲッティ　乾', 12.9, 1.8, 73.1, 347);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［マカロニ・スパゲッティ類］　マカロニ・スパゲッティ　ゆで', 5.8, 0.9, 32.2, 150);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［マカロニ・スパゲッティ類］　マカロニ・スパゲッティ　ソテー', (5.5), (5.8), (30.5), 186);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［マカロニ・スパゲッティ類］　生パスタ　生', 7.8, 1.9, 46.9, 232);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［ふ類］　生ふ', 12.7, 0.8, 26.2, 161);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［ふ類］　焼きふ　釜焼きふ', 28.5, 2.7, 56.9, 357);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［ふ類］　焼きふ　板ふ', 25.6, 3.3, 57.3, 351);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［ふ類］　焼きふ　車ふ', 30.2, 3.4, 54.2, 361);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［ふ類］　油ふ', 22.7, 35.3, 34.4, 547);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　小麦はいが', 32.0, 11.6, 48.3, 391);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　小麦たんぱく　粉末状', 72.0, 9.7, 10.6, 398);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　小麦たんぱく　粒状', 20.0, 2.0, 1.8, 101);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　小麦たんぱく　ペースト状', 25.0, 4.1, 3.9, 145);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　かやきせんべい', 10.6, 1.9, 75.1, 359);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　ぎょうざの皮　生', 9.3, 1.4, 57.0, 275);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　しゅうまいの皮　生', 8.3, 1.4, 58.9, 275);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　春巻きの皮　生', 8.3, 1.6, 62.2, 288);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　春巻きの皮　揚げ', 7.2, 30.7, 53.7, 512);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　ピザ生地', 9.1, 3.0, 51.1, 265);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　ちくわぶ', 7.1, 1.2, 31.1, 160);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　パン粉　生', 11.0, 5.1, 47.6, 277);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　パン粉　半生', 12.5, 5.8, 54.3, 315);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　パン粉　乾燥', 14.9, 4.1, 67.4, 349);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こむぎ　［その他］　冷めん　生', 3.9, 0.7, 57.6, 249);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲穀粒］　玄米', 6.8, 2.7, 74.3, 346);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲穀粒］　半つき米', 6.5, 1.8, 75.9, 345);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲穀粒］　七分つき米', 6.3, 1.5, 76.6, 348);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲穀粒］　精白米　うるち米', 6.1, 0.9, 77.6, 342);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲穀粒］　精白米　もち米', 6.4, 1.2, 77.2, 343);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲穀粒］　精白米　インディカ米', 7.4, 0.9, 77.7, 347);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲穀粒］　はいが精米', 6.5, 2.0, 75.8, 343);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲穀粒］　発芽玄米', 6.5, 3.3, 74.3, 339);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲穀粒］　赤米', 8.5, 3.3, 71.9, 344);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲穀粒］　黒米', 7.8, 3.2, 72.0, 341);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲めし］　玄米', 2.8, 1.0, 35.6, 152);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲めし］　半つき米', 2.7, 0.6, 36.4, 154);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲めし］　七分つき米', 2.6, 0.5, 36.7, 160);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲めし］　精白米　インディカ米', 3.8, 0.4, 41.5, 184);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲めし］　精白米　うるち米', 2.5, 0.3, 37.1, 156);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲めし］　精白米　もち米', 3.5, 0.5, 43.9, 188);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲めし］　はいが精米', 2.7, 0.6, 36.4, 159);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲めし］　発芽玄米', 3.0, 1.4, 35.0, 161);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲めし］　赤米', 3.8, 1.3, 32.7, 150);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲めし］　黒米', 3.6, 1.4, 32.2, 150);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲軟めし］　精白米', (1.8), (0.3), (26.4), 113);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲全かゆ］　玄米', (1.2), (0.4), (15.2), 64);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲全かゆ］　半つき米', (1.1), (0.3), (15.5), 65);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲全かゆ］　七分つき米', (1.1), (0.2), (15.6), 68);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲全かゆ］　精白米', (1.1), (0.1), (15.7), 65);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲五分かゆ］　玄米', (0.6), (0.2), (7.6), 32);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲五分かゆ］　半つき米', (0.6), (0.1), (7.7), 32);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲五分かゆ］　七分つき米', (0.6), (0.1), (7.7), 32);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲五分かゆ］　精白米', (0.5), (0.1), (7.9), 33);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲おもゆ］　玄米', (0.4), (0.1), (4.4), 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲おもゆ］　半つき米', (0.3), (0.1), (4.6), 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲おもゆ］　七分つき米', (0.3), (0.1), (4.6), 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［水稲おもゆ］　精白米', (0.3), 0, (4.7), 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［陸稲穀粒］　玄米', 10.1, 2.7, 71.1, 357);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［陸稲穀粒］　半つき米', 9.6, 1.8, 72.9, 356);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［陸稲穀粒］　七分つき米', 9.5, 1.5, 73.4, 359);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［陸稲穀粒］　精白米', 9.3, 0.9, 74.5, 331);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［陸稲めし］　玄米', 4.1, 1.0, 34.3, 156);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［陸稲めし］　半つき米', 3.8, 0.6, 35.3, 157);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［陸稲めし］　七分つき米', 3.6, 0.5, 35.7, 155);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［陸稲めし］　精白米', 3.5, 0.3, 36.1, 157);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　アルファ化米　一般用', 6.0, 1.0, 84.8, 358);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　アルファ化米　学校給食用強化品', 6.0, 1.0, 84.8, 358);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　水稲全かゆ　レトルト　玄米', 0.9, 0.4, 10.6, 45);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　水稲全かゆ　レトルト　精白米', 0.6, 0.1, 8.6, 37);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　おにぎり', 2.7, 0.3, 39.4, 170);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　焼きおにぎり', 3.1, 0.3, 39.5, 166);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　きりたんぽ', 3.2, 0.4, 46.2, 200);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　上新粉', 6.2, 0.9, 78.5, 343);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　玄米粉', 7.1, 2.9, 84.1, 370);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　米粉', 6.0, 0.7, 81.9, 356);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　米粉パン　食パン', (10.7), (5.1), (41.6), 247);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　米粉パン　ロールパン', (8.8), (6.7), (42.0), 256);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　米粉パン　小麦グルテン不使用のもの', 3.4, 3.1, 51.3, 247);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　米粉めん', 3.6, 0.7, 58.4, 252);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　ビーフン', 7.0, 1.6, 79.9, 360);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　ライスペーパー', 0.5, 0.3, 84.3, 339);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［うるち米製品］　米こうじ', 5.8, 1.7, 59.2, 260);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［もち米製品］　もち', 4.0, 0.6, 50.8, 223);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［もち米製品］　赤飯', 4.3, 0.6, 41.9, 186);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［もち米製品］　あくまき', 2.3, 1.8, 25.7, 131);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［もち米製品］　白玉粉', 6.3, 1.0, 80.0, 347);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［もち米製品］　道明寺粉', 7.1, 0.7, 80.4, 349);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こめ　［その他］　米ぬか', 13.4, 19.6, 48.8, 374);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そば　そば粉　全層粉', 12.0, 3.1, 69.6, 339);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そば　そば粉　内層粉', 6.0, 1.6, 77.6, 342);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そば　そば粉　中層粉', 10.2, 2.7, 71.6, 334);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そば　そば粉　表層粉', 15.0, 3.6, 65.1, 337);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そば　そば米', 9.6, 2.5, 73.7, 347);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そば　そば　生', 9.8, 1.9, 54.5, 271);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そば　そば　ゆで', 4.8, 1.0, 26.0, 130);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そば　そば　半生そば', (10.5), (3.8), (61.8), 325);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そば　干しそば　乾', 14.0, 2.3, 66.7, 344);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そば　干しそば　ゆで', 4.8, 0.7, 22.1, 113);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうもろこし　玄穀　黄色種', 8.6, 5.0, 70.6, 341);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうもろこし　玄穀　白色種', 8.6, 5.0, 70.6, 341);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうもろこし　コーンミール　黄色種', 8.3, 4.0, 72.4, 375);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうもろこし　コーンミール　白色種', 8.3, 4.0, 72.4, 375);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうもろこし　コーングリッツ　黄色種', 8.2, 1.0, 76.4, 352);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうもろこし　コーングリッツ　白色種', 8.2, 1.0, 76.4, 352);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうもろこし　コーンフラワー　黄色種', 6.6, 2.8, 76.1, 347);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうもろこし　コーンフラワー　白色種', 6.6, 2.8, 76.1, 347);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうもろこし　ジャイアントコーン　フライ　味付け', 5.7, 11.8, 76.6, 409);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうもろこし　ポップコーン', 10.2, 22.8, 59.6, 472);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうもろこし　コーンフレーク', 7.8, 1.7, 83.6, 380);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はとむぎ　精白粒', 13.3, 1.3, 72.2, 353);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ひえ　精白粒', 9.4, 3.3, 73.2, 361);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('もろこし　玄穀', 10.3, 4.7, 71.1, 344);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('もろこし　精白粒', 9.5, 2.6, 74.1, 348);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ライむぎ　全粒粉', 12.7, 2.7, 70.7, 317);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ライむぎ　ライ麦粉', 8.5, 1.6, 75.8, 324);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　アメリカほどいも　塊根　生', 5.9, 0.6, 35.6, 146);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　アメリカほどいも　塊根　ゆで', 6.0, 0.8, 34.5, 144);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　きくいも　塊茎　生', 1.9, 0.4, 14.7, 66);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　きくいも　塊茎　水煮', 1.6, 0.5, 11.3, 51);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　こんにゃく　精粉', 3.0, 0.1, 85.3, 194);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　こんにゃく　板こんにゃく　精粉こんにゃく', 0.1, 0, 2.3, 5);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　こんにゃく　板こんにゃく　生いもこんにゃく', 0.1, 0.1, 3.3, 8);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　こんにゃく　赤こんにゃく', 0.1, 0, 2.5, 6);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　こんにゃく　凍みこんにゃく　乾', 3.3, 1.4, 77.1, 192);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　こんにゃく　凍みこんにゃく　ゆで', 0.7, 0.3, 16.8, 42);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　こんにゃく　しらたき', 0.2, 0, 3.0, 7);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さつまいも類）　さつまいも　塊根　皮つき　生', 0.9, 0.5, 33.1, 127);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さつまいも類）　さつまいも　塊根　皮つき　蒸し', 0.9, 0.2, 33.7, 129);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さつまいも類）　さつまいも　塊根　皮つき　天ぷら', 1.4, 6.8, 38.4, 205);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さつまいも類）　さつまいも　塊根　皮なし　生', 1.2, 0.2, 31.9, 126);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さつまいも類）　さつまいも　塊根　皮なし　蒸し', 1.2, 0.2, 31.9, 131);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さつまいも類）　さつまいも　塊根　皮なし　焼き', 1.4, 0.2, 39.0, 151);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さつまいも類）　さつまいも　蒸し切干', 3.1, 0.6, 71.9, 277);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さつまいも類）　むらさきいも　塊根　皮なし　生', 1.2, 0.3, 31.7, 123);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さつまいも類）　むらさきいも　塊根　皮なし　蒸し', 1.2, 0.3, 31.4, 122);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さといも類）　さといも　球茎　生', 1.5, 0.1, 13.1, 53);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さといも類）　さといも　球茎　水煮', 1.5, 0.1, 13.4, 52);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さといも類）　さといも　球茎　冷凍', 2.2, 0.1, 16, 56);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さといも類）　セレベス　球茎　生', 2.2, 0.3, 19.8, 80);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さといも類）　セレベス　球茎　水煮', 2.1, 0.3, 19.1, 77);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さといも類）　たけのこいも　球茎　生', 1.7, 0.4, 23.5, 97);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さといも類）　たけのこいも　球茎　水煮', 1.6, 0.4, 21.8, 86);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さといも類）　みずいも　球茎　生', 0.7, 0.4, 27.6, 111);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さといも類）　みずいも　球茎　水煮', 0.7, 0.4, 26.1, 101);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さといも類）　やつがしら　球茎　生', 3.0, 0.7, 20.5, 94);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（さといも類）　やつがしら　球茎　水煮', 2.7, 0.6, 20.0, 92);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　じゃがいも　塊茎　皮つき　生', 1.8, 0.1, 15.9, 51);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　じゃがいも　塊茎　皮つき　電子レンジ調理', 2.1, 0.2, 19.2, 78);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　じゃがいも　塊茎　皮つき　フライドポテト　（生を揚げたもの）', 2.7, 5.6, 25.4, 153);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　じゃがいも　塊茎　皮なし　生', 1.8, 0.1, 17.3, 59);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　じゃがいも　塊茎　皮なし　水煮', 1.7, 0.1, 16.9, 71);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　じゃがいも　塊茎　皮なし　蒸し', 1.9, 0.3, 18.1, 76);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　じゃがいも　塊茎　皮なし　電子レンジ調理', 1.9, 0.1, 19.0, 78);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　じゃがいも　塊茎　皮なし　フライドポテト　（生を揚げたもの）', 2.7, 5.9, 26.2, 159);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　じゃがいも　塊茎　皮なし　フライドポテト　（市販冷凍食品を揚げたもの）', 2.9, 10.6, 32.4, 229);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　じゃがいも　乾燥マッシュポテト', 6.6, 0.6, 82.8, 347);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　ヤーコン　塊根　生', 0.6, 0.3, 12.4, 52);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　ヤーコン　塊根　水煮', 0.6, 0.3, 9.9, 42);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（やまのいも類）　ながいも　いちょういも　塊根　生', 4.5, 0.5, 22.6, 108);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（やまのいも類）　ながいも　ながいも　塊根　生', 2.2, 0.3, 13.9, 64);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（やまのいも類）　ながいも　ながいも　塊根　水煮', 2.0, 0.3, 12.6, 58);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（やまのいも類）　ながいも　やまといも　塊根　生', 4.5, 0.2, 27.1, 119);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（やまのいも類）　じねんじょ　塊根　生', 2.8, 0.7, 26.7, 118);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜いも類＞　（やまのいも類）　だいじょ　塊根　生', 2.6, 0.1, 25.0, 102);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉類）　おおうばゆりでん粉', 0.1, 0.1, 83.6, 327);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉類）　キャッサバでん粉', 0.1, 0.2, 85.3, 354);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉類）　くずでん粉', 0.2, 0.2, 85.6, 356);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉類）　米でん粉', 0.2, 0.7, 89.3, 375);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉類）　小麦でん粉', 0.2, 0.5, 86.0, 360);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉類）　サゴでん粉', 0.1, 0.2, 86.1, 357);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉類）　さつまいもでん粉', 0.1, 0.2, 82.0, 340);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉類）　じゃがいもでん粉', 0.1, 0.1, 81.6, 338);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉類）　とうもろこしでん粉', 0.1, 0.7, 86.3, 363);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　くずきり　乾', 0.2, 0.2, 87.7, 341);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　くずきり　ゆで', 0.1, 0.1, 33.3, 133);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　ごま豆腐', 1.5, 4.3, 9.1, 75);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　タピオカパール　乾', 0, 0.2, 87.8, 352);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　タピオカパール　ゆで', 0, 0, 15.4, 61);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　でん粉めん　生', 0.1, 0.2, 32.2, 129);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　でん粉めん　乾', 0.2, 0.3, 86.7, 347);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　でん粉めん　乾　ゆで', 0, 0.2, 20.6, 83);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　はるさめ　緑豆はるさめ　乾', 0.2, 0.4, 87.5, 344);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　はるさめ　緑豆はるさめ　ゆで', 0, 0.1, 20.6, 78);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　はるさめ　普通はるさめ　乾', 0, 0.2, 86.6, 346);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('＜でん粉・でん粉製品＞　（でん粉製品）　はるさめ　普通はるさめ　ゆで', 0, 0, 19.9, 76);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　黒砂糖', 1.7, 0, 90.3, 352);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　てんさい含蜜糖', 0.9, 0, 96.9, 357);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　和三盆糖', 0.2, 0, 99.0, 393);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　車糖　上白糖', (0), (0), 99.3, 391);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　車糖　三温糖', 0, (0), 99.0, 390);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　ざらめ糖　グラニュー糖', (0), (0), 100, 394);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　ざらめ糖　白ざら糖', (0), (0), 100, 393);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　ざらめ糖　中ざら糖', (0), (0), 100, 393);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　加工糖　角砂糖', (0), (0), 100, 394);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　加工糖　氷砂糖', (0), (0), 100, 394);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　加工糖　コーヒーシュガー', 0.1, (0), 99.8, 394);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　加工糖　粉糖', (0), (0), 99.7, 393);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　液糖　しょ糖型液糖', (0), (0), 67.9, 267);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　液糖　転化型液糖', (0), (0), 76.6, 294);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（砂糖類）　氷糖みつ', 0.2, (0), 68.2, 274);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　還元麦芽糖', 0, 0, 100, 208);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　還元水あめ', 0, 0, 69.9, 210);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　粉あめ', (0), (0), 97.0, 397);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　水あめ　酵素糖化', (0), (0), 85.0, 342);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　水あめ　酸糖化', (0), (0), 85.0, 341);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　ぶどう糖　全糖', (0), (0), 91.0, 342);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　ぶどう糖　含水結晶', (0), (0), 91.3, 342);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　ぶどう糖　無水結晶', (0), (0), 99.7, 374);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　果糖', (0), (0), 99.9, 375);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　異性化液糖　ぶどう糖果糖液糖', 0, 0, 75.0, 283);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　異性化液糖　果糖ぶどう糖液糖', 0, 0, 75.0, 283);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（でん粉糖類）　異性化液糖　高果糖液糖', 0, 0, 75.0, 282);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（その他）　黒蜜', 1.0, 0, 50.5, 199);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（その他）　はちみつ', 0.3, 0, 81.9, 329);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（その他）　はちみつ　国産品　', 0.1, 0, 81.7, 328);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（その他）　メープルシロップ', 0.1, 0, 66.3, 266);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あずき　全粒　乾', 20.8, 2.0, 59.6, 304);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あずき　全粒　ゆで', 8.6, 0.8, 25.6, 124);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あずき　ゆで小豆缶詰', 4.4, 0.4, 49.2, 202);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あずき　あん　こし生あん', 9.8, 0.6, 27.1, 147);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あずき　あん　さらしあん　（乾燥あん）', 23.5, 1.0, 66.8, 335);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あずき　あん　こし練りあん　（並あん）', (5.6), (0.3), (58.8), 255);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あずき　あん　こし練りあん　（中割りあん）', (5.1), (0.3), (61.1), 262);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あずき　あん　こし練りあん　（もなかあん）', (5.1), (0.3), (68.6), 292);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あずき　あん　つぶし生あん', 8.6, 0.5, 24.5, 115);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あずき　あん　つぶし練りあん', 5.6, 0.6, 54.0, 239);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いんげんまめ　全粒　乾', 22.1, 2.5, 56.4, 280);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いんげんまめ　全粒　ゆで', 9.3, 1.2, 24.5, 127);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いんげんまめ　うずら豆', 6.7, 1.3, 49.6, 214);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いんげんまめ　こし生あん', 9.4, 0.9, 27.0, 135);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いんげんまめ　豆きんとん', 4.9, 0.5, 56.2, 238);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えんどう　全粒　青えんどう　乾', 21.7, 2.3, 60.4, 310);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えんどう　全粒　青えんどう　ゆで', 9.2, 1.0, 25.2, 129);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えんどう　全粒　赤えんどう　乾', 21.7, 2.3, 60.4, 310);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えんどう　全粒　赤えんどう　ゆで', 9.2, 1.0, 25.2, 129);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えんどう　グリンピース（揚げ豆）', 20.8, 11.6, 58.8, 375);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えんどう　塩豆', 23.3, 2.4, 61.5, 321);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えんどう　うぐいす豆', 5.6, 0.7, 52.9, 228);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えんどう　うぐいすあん', 5.4, 0.8, 54.8, 221);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ささげ　全粒　乾', 23.9, 2.0, 55.0, 280);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ささげ　全粒　ゆで', 10.2, 0.9, 23.8, 130);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そらまめ　全粒　乾', 26.0, 2.0, 55.9, 323);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そらまめ　フライビーンズ', 24.7, 20.8, 46.4, 436);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そらまめ　おたふく豆', 7.9, 1.2, 52.2, 237);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そらまめ　ふき豆', 9.6, 1.6, 52.5, 251);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そらまめ　しょうゆ豆', 9.8, 0.9, 37.1, 173);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　全粒　青大豆　国産　乾', 33.5, 19.3, 30.1, 354);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　全粒　青大豆　国産　ゆで', 15.0, 8.2, 9.9, 145);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　全粒　黄大豆　国産　乾', 33.8, 19.7, 29.5, 372);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　全粒　黄大豆　国産　ゆで', 14.8, 9.8, 8.4, 163);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　全粒　黄大豆　米国産　乾', 33.0, 21.7, 28.8, 402);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　全粒　黄大豆　中国産　乾', 32.8, 19.5, 30.8, 391);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　全粒　黄大豆　ブラジル産　乾', 33.6, 22.6, 30.7, 414);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　全粒　黒大豆　国産　乾', 33.9, 18.8, 28.9, 349);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　全粒　黒大豆　国産　ゆで', 14.7, 8.6, 9.8, 155);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　いり大豆　青大豆', 37.7, 20.7, 33.9, 425);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　いり大豆　黄大豆', 37.5, 21.6, 33.3, 429);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　いり大豆　黒大豆', 36.4, 22.0, 34.3, 431);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　水煮缶詰　黄大豆', 12.9, 6.7, 7.7, 124);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　蒸し大豆　黄大豆', 16.6, 9.8, 13.8, 186);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　きな粉　青大豆　全粒大豆', 37.0, 22.8, 29.3, 424);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　きな粉　青大豆　脱皮大豆', 36.6, 24.6, 28.3, 418);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　きな粉　黄大豆　全粒大豆', 36.7, 25.7, 28.5, 451);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　きな粉　黄大豆　脱皮大豆', 37.5, 25.1, 29.5, 456);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　きな粉（砂糖入り）　青きな粉', (18.5), (11.4), (64.3), 392);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　きな粉（砂糖入り）　きな粉', (18.3), (12.9), (63.9), 406);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　大豆はいが', 37.8, 14.7, 39.5, 404);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［全粒・全粒製品］　ぶどう豆', 14.1, 9.4, 37.0, 265);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　木綿豆腐', 7.0, 4.9, 1.5, 73);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　木綿豆腐　（凝固剤：塩化マグネシウム）', 7.0, 4.9, 1.5, 73);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　木綿豆腐　（凝固剤：硫酸カルシウム）', 7.0, 4.9, 1.5, 73);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　絹ごし豆腐', 5.3, 3.5, 2.0, 56);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　絹ごし豆腐　（凝固剤：塩化マグネシウム）', 5.3, 3.5, 2.0, 56);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　絹ごし豆腐　（凝固剤：硫酸カルシウム）', 5.3, 3.5, 2.0, 56);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　ソフト豆腐', 5.1, 3.3, 2.0, 56);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　充てん豆腐', 5.0, 3.1, 2.5, 56);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　沖縄豆腐', 9.1, 7.2, 0.7, 99);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　ゆし豆腐', 4.3, 2.8, 1.7, 47);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　焼き豆腐', 7.8, 5.7, 1.0, 82);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　生揚げ', 10.7, 11.3, 0.9, 143);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　絹生揚げ', 7.9, 7.7, 2.9, 103);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　油揚げ　生', 23.4, 34.4, 0.4, 377);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　油揚げ　油抜き　生', 18.2, 23.4, 0, 266);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　油揚げ　油抜き　ゆで', 12.4, 13.8, 0.3, 164);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　油揚げ　油抜き　焼き', 24.9, 32.2, 0.7, 361);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　油揚げ　甘煮', 11.2, 13.0, 19.1, 231);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　がんもどき', 15.3, 17.8, 1.6, 223);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　凍り豆腐　乾', 50.5, 34.1, 4.2, 496);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　凍り豆腐　水煮', 10.7, 7.3, 1.1, 104);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　豆腐よう', 9.5, 8.3, 19.1, 183);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　豆腐竹輪　蒸し', 14.9, 4.4, 6.7, 121);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　豆腐竹輪　焼き', 16.1, 4.9, 7.5, 133);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［豆腐・油揚げ類］　ろくじょう豆腐', 34.7, 21.5, 3.8, 332);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［納豆類］　糸引き納豆', 16.5, 10.0, 12.1, 184);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［納豆類］　挽きわり納豆', 16.6, 10.0, 10.5, 185);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［納豆類］　五斗納豆', 15.3, 8.1, 24.0, 214);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［納豆類］　塩納豆', 8.3, 4.4, 20.2, 137);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［納豆類］　寺納豆', 18.6, 8.1, 31.5, 248);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［納豆類］　干し納豆', 33, 16.8, 29.3, 357);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　おから　生', 6.1, 3.6, 13.8, 88);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　おから　乾燥', 23.1, 13.6, 52.3, 333);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　豆乳　豆乳', 3.6, 2.8, 2.3, 43);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　豆乳　調製豆乳', 3.2, 3.6, 4.8, 61);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　豆乳　豆乳飲料・麦芽コーヒー', 2.2, 2.2, 7.8, 57);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　大豆たんぱく　粒状大豆たんぱく', 46.3, 3.0, 36.7, 318);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　大豆たんぱく　濃縮大豆たんぱく', 58.2, 1.7, 27.9, 313);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　大豆たんぱく　分離大豆たんぱく　塩分無調整タイプ', 79.1, 3.0, 7.5, 335);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　大豆たんぱく　分離大豆たんぱく　塩分調整タイプ', 79.1, 3.0, 7.5, 335);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　大豆たんぱく　繊維状大豆たんぱく', 59.3, 5.0, 25.2, 365);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　湯葉　生', 21.8, 13.7, 4.1, 218);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　湯葉　干し　乾', 50.4, 32.1, 7.2, 485);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　湯葉　干し　湯戻し', 15.7, 10.6, 0.1, 151);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　金山寺みそ', 6.9, 3.2, 50.0, 247);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　ひしおみそ', 6.5, 2.7, 38.8, 198);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('だいず　［その他］　テンペ', 15.8, 9.0, 15.4, 180);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('つるあずき　全粒　乾', 20.8, 1.6, 61.8, 297);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('つるあずき　全粒　ゆで', 9.7, 1.0, 27.5, 132);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ひよこまめ　全粒　乾', 20.0, 5.2, 61.5, 336);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ひよこまめ　全粒　ゆで', 9.5, 2.5, 27.4, 149);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ひよこまめ　全粒　フライ　味付け', 18.8, 10.4, 62.6, 366);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('べにばないんげん　全粒　乾', 17.2, 1.7, 61.2, 273);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('べにばないんげん　全粒　ゆで', 6.2, 0.6, 22.3, 103);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('やぶまめ　乾', 23.4, 10.1, 49.5, 383);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('らいまめ　全粒　乾', 21.9, 1.8, 60.8, 306);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('らいまめ　全粒　ゆで', 9.6, 0.9, 26.0, 122);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('りょくとう　全粒　乾', 25.1, 1.5, 59.1, 319);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('りょくとう　全粒　ゆで', 10.2, 0.6, 22.5, 125);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('レンズまめ　全粒　乾', 23.2, 1.5, 60.7, 313);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('レンズまめ　全粒　ゆで', 11.2, 0.8, 29.1, 149);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アーモンド　乾', 19.6, 51.8, 20.9, 609);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アーモンド　フライ　味付け', 21.3, 55.7, 17.9, 626);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アーモンド　いり　無塩', 20.3, 54.1, 20.7, 608);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あさ　乾', 29.9, 28.3, 31.7, 450);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あまに　いり', 21.8, 43.3, 30.4, 540);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えごま　乾', 17.7, 43.4, 29.4, 523);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('カシューナッツ　フライ　味付け', 19.8, 47.6, 26.7, 591);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぼちゃ　いり　味付け', 26.5, 51.8, 12.0, 590);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かや　いり', 8.7, 64.9, 22.6, 629);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ぎんなん　生', 4.7, 1.6, 34.8, 168);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ぎんなん　ゆで', 4.6, 1.5, 35.8, 169);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（くり類）　日本ぐり　生', 2.8, 0.5, 36.9, 147);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（くり類）　日本ぐり　ゆで', 3.5, 0.6, 36.7, 152);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（くり類）　日本ぐり　甘露煮', 1.8, 0.4, 56.8, 232);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（くり類）　中国ぐり　甘ぐり', 4.9, 0.9, 48.5, 207);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('くるみ　いり', 14.6, 68.8, 11.7, 713);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('けし　乾', 19.3, 49.1, 21.8, 555);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ココナッツ　ココナッツパウダー', 6.1, 65.8, 23.7, 676);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ごま　乾', 19.8, 53.8, 16.5, 604);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ごま　いり', 20.3, 54.2, 18.5, 605);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ごま　むき', 19.3, 54.9, 18.8, 570);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ごま　ねり', 19.0, 61.0, 15.6, 646);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('しい　生', 3.2, 0.8, 57.6, 244);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('すいか　いり　味付け', 29.6, 46.4, 13.4, 528);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('チアシード　乾', 19.4, 33.9, 34.5, 446);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とち　蒸し', 1.7, 1.9, 34.2, 148);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はす　未熟　生', 5.9, 0.5, 14.9, 81);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はす　成熟　乾', 18.3, 2.3, 64.3, 327);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はす　成熟　ゆで', 7.3, 0.8, 25.0, 118);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ひし類）　ひし　生', 5.8, 0.5, 40.6, 183);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ひし類）　とうびし　生', 2.7, 0.4, 31.4, 122);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ひし類）　とうびし　ゆで', 2.7, 0.3, 30.5, 120);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ピスタチオ　いり　味付け', 17.4, 56.1, 20.9, 617);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ひまわり　フライ　味付け', 20.1, 56.3, 17.2, 603);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ブラジルナッツ　フライ　味付け', 14.9, 69.1, 9.6, 703);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ヘーゼルナッツ　フライ　味付け', 13.6, 69.3, 13.9, 701);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ペカン　フライ　味付け', 9.6, 73.4, 13.3, 716);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('マカダミアナッツ　いり　味付け', 8.3, 76.7, 12.2, 751);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('まつ　生', 15.8, 68.2, 10.6, 681);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('まつ　いり', 14.6, 72.5, 8.1, 724);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('らっかせい　大粒種　乾', 25.2, 47.0, 19.4, 572);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('らっかせい　大粒種　いり', 25.0, 49.6, 21.3, 613);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('らっかせい　小粒種　乾', 25.4, 47.5, 18.8, 573);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('らっかせい　小粒種　いり', 26.5, 49.4, 19.6, 607);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('らっかせい　バターピーナッツ', 23.3, 53.2, 18.3, 609);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('らっかせい　ピーナッツバター', 20.6, 50.4, 24.9, 599);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アーティチョーク　花らい　生', 2.3, 0.2, 11.3, 39);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アーティチョーク　花らい　ゆで', 2.1, 0.1, 10.8, 35);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アイスプラント　生', 0.5, 0.3, 1.2, 5);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あさつき　葉　生', 4.2, 0.3, 5.6, 34);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あさつき　葉　ゆで', 4.2, 0.3, 7.3, 41);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あしたば　茎葉　生', 3.3, 0.1, 6.7, 30);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あしたば　茎葉　ゆで', 2.9, 0.1, 6.6, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アスパラガス　若茎　生', 2.6, 0.2, 3.9, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アスパラガス　若茎　ゆで', 2.6, 0.1, 4.6, 25);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アスパラガス　若茎　油いため', 2.9, 3.9, 4.1, 54);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アスパラガス　水煮缶詰', 2.4, 0.1, 4.3, 24);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アロエ　葉　生', 0, 0.1, 0.7, 3);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いんげんまめ　さやいんげん　若ざや　生', 1.8, 0.1, 5.1, 23);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いんげんまめ　さやいんげん　若ざや　ゆで', 1.8, 0.2, 5.5, 24);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（うど類）　うど　茎　生', 0.8, 0.1, 4.3, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（うど類）　うど　茎　水さらし', 0.6, 0, 3.4, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（うど類）　やまうど　茎　生', 1.1, 0.1, 4.3, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('うるい　葉　生', 1.9, 0.4, 4.0, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えだまめ　生', 11.7, 6.2, 8.8, 125);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えだまめ　ゆで', 11.5, 6.1, 8.9, 118);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('えだまめ　冷凍', 13.0, 7.6, 10.6, 143);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('エンダイブ　葉　生', 1.2, 0.2, 2.9, 14);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　トウミョウ　茎葉　生', 3.8, 0.4, 4.0, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　トウミョウ　芽ばえ　生', 3.8, 0.4, 3.2, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　トウミョウ　芽ばえ　ゆで', 3.6, 0.6, 3.8, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　トウミョウ　芽ばえ　油いため', 5.0, 5.9, 4.3, 84);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　さやえんどう　若ざや　生', 3.1, 0.2, 7.5, 38);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　さやえんどう　若ざや　ゆで', 3.2, 0.2, 7.0, 36);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　スナップえんどう　若ざや　生', 2.9, 0.1, 9.9, 47);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　グリンピース　生', 6.9, 0.4, 15.3, 76);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　グリンピース　ゆで', 8.3, 0.2, 18.5, 99);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　グリンピース　冷凍', 5.8, 0.7, 17.1, 80);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　グリンピース　冷凍　ゆで', 6.2, 0.7, 17.8, 82);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　グリンピース　冷凍　油いため', 6.3, 4.6, 18.2, 114);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（えんどう類）　グリンピース　水煮缶詰', 3.6, 0.4, 19.7, 82);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おおさかしろな　葉　生', 1.4, 0.2, 2.2, 12);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おおさかしろな　葉　ゆで', 1.6, 0.3, 3.1, 16);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おおさかしろな　塩漬', 1.3, 0.3, 4.5, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おかひじき　茎葉　生', 1.4, 0.2, 3.4, 16);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('おかひじき　茎葉　ゆで', 1.2, 0.1, 3.8, 16);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('オクラ　果実　生', 2.1, 0.2, 6.6, 26);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('オクラ　果実　ゆで', 2.1, 0.1, 7.6, 25);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　葉　生', 2.3, 0.1, 3.9, 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　葉　ゆで', 2.3, 0.1, 4.4, 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　根　皮つき　生', 0.7, 0.1, 4.6, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　根　皮つき　ゆで', 0.7, 0.1, 4.7, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　根　皮なし　生', 0.6, 0.1, 4.8, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　根　皮なし　ゆで', 0.6, 0.1, 5.0, 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　漬物　塩漬　葉', 2.3, 0.2, 6.0, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　漬物　塩漬　根　皮つき', 1.0, 0.2, 4.9, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　漬物　塩漬　根　皮なし', 0.8, 0.1, 4.7, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　漬物　ぬかみそ漬　葉', 3.3, 0.1, 7.1, 35);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　漬物　ぬかみそ漬　根　皮つき', 1.5, 0.1, 5.9, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かぶ　漬物　ぬかみそ漬　根　皮なし', 1.4, 0.1, 6.9, 31);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（かぼちゃ類）　日本かぼちゃ　果実　生', 1.6, 0.1, 10.9, 41);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（かぼちゃ類）　日本かぼちゃ　果実　ゆで', 1.9, 0.1, 13.3, 55);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（かぼちゃ類）　西洋かぼちゃ　果実　生', 1.9, 0.3, 20.6, 78);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（かぼちゃ類）　西洋かぼちゃ　果実　ゆで', 1.6, 0.3, 21.3, 80);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（かぼちゃ類）　西洋かぼちゃ　果実　焼き', 2.5, 0.4, 27.7, 105);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（かぼちゃ類）　西洋かぼちゃ　果実　冷凍', 2.2, 0.3, 18.5, 75);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（かぼちゃ類）　そうめんかぼちゃ　果実　生', 0.7, 0.1, 6.1, 25);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('からしな　葉　生', 3.3, 0.1, 4.7, 26);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('からしな　塩漬', 4.0, 0.1, 7.2, 36);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('カリフラワー　花序　生', 3.0, 0.1, 5.2, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('カリフラワー　花序　ゆで', 2.7, 0.1, 5.1, 26);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かんぴょう　乾', 6.3, 0.2, 68.1, 239);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かんぴょう　ゆで', 0.7, 0, 7.2, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('かんぴょう　甘煮', 2.3, 0.2, 36.5, 146);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('きく　花びら　生', 1.4, 0, 6.5, 25);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('きく　花びら　ゆで', 1.0, 0, 5.7, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('きく　菊のり', 11.6, 0.2, 73.5, 283);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（キャベツ類）　キャベツ　結球葉　生', 1.2, 0.1, 5.2, 23);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（キャベツ類）　キャベツ　結球葉　ゆで', 0.9, 0.2, 4.6, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（キャベツ類）　キャベツ　結球葉　油いため', 1.6, 6.0, 5.9, 78);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（キャベツ類）　キャベツ　結球葉　カット　常法洗浄', 1.1, 0.1, 3.6, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（キャベツ類）　キャベツ　結球葉　カット　次亜塩素酸洗浄', 1, 0.2, 3.2, 14);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（キャベツ類）　グリーンボール　結球葉　生', 1.4, 0.1, 4.3, 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（キャベツ類）　レッドキャベツ　結球葉　生', 2.0, 0.1, 6.7, 30);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('きゅうり　果実　生', 1.0, 0.1, 3.0, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('きゅうり　漬物　塩漬', 1.0, 0.1, 3.7, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('きゅうり　漬物　しょうゆ漬', 3.2, 0.4, 10.8, 51);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('きゅうり　漬物　ぬかみそ漬', 1.5, 0.1, 6.2, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('きゅうり　漬物　ピクルス　スイート型', 0.3, 0.1, 18.3, 70);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('きゅうり　漬物　ピクルス　サワー型', 1.4, 0, 2.5, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ぎょうじゃにんにく　葉　生', 3.5, 0.2, 6.6, 35);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('キンサイ　茎葉　生', 1.1, 0.4, 3.5, 16);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('キンサイ　茎葉　ゆで', 1.1, 0.4, 3.5, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('クレソン　茎葉　生', 2.1, 0.1, 2.5, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('くわい　塊茎　生', 6.3, 0.1, 26.6, 128);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('くわい　塊茎　ゆで', 6.2, 0.1, 27.2, 129);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ケール　葉　生', 2.1, 0.4, 5.6, 26);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('コールラビ　球茎　生', 1.0, 0, 5.1, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('コールラビ　球茎　ゆで', 1.0, 0, 5.2, 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こごみ　若芽　生', 3.0, 0.2, 5.3, 25);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ごぼう類）　ごぼう　根　生', 1.8, 0.1, 15.4, 58);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ごぼう類）　ごぼう　根　ゆで', 1.5, 0.2, 13.7, 50);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ごぼう類）　堀川ごぼう　根　生', 3.2, 0.2, 19.1, 55);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こまつな　葉　生', 1.5, 0.2, 2.4, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('こまつな　葉　ゆで', 1.6, 0.1, 3.0, 14);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('コリアンダー　葉　生', 1.4, 0.4, 4.6, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ザーサイ　漬物', 2.5, 0.1, 4.6, 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('さんとうさい　葉　生', 1.0, 0.2, 2.7, 12);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('さんとうさい　葉　ゆで', 1.4, 0.3, 2.9, 14);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('さんとうさい　塩漬', 1.5, 0.3, 4.0, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('しかくまめ　若ざや　生', 2.4, 0.1, 3.8, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ししとう類）　ししとう　果実　生', 1.9, 0.3, 5.7, 24);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ししとう類）　ししとう　果実　油いため', 1.9, 3.2, 5.8, 51);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ししとう類）　万願寺とうがらし　果実　生', 1.3, 0.3, 6.2, 26);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('しそ　葉　生', 3.9, 0.1, 7.5, 32);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('しそ　実　生', 3.4, 0.1, 8.9, 32);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('じゅうろくささげ　若ざや　生', 2.5, 0.1, 4.8, 22);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('じゅうろくささげ　若ざや　ゆで', 2.8, 0.1, 6.2, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('しゅんぎく　葉　生', 2.3, 0.3, 3.9, 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('しゅんぎく　葉　ゆで', 2.7, 0.5, 4.5, 25);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('じゅんさい　若葉　水煮びん詰', 0.4, 0, 1.0, 4);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（しょうが類）　葉しょうが　根茎　生', 0.5, 0.2, 2.1, 9);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（しょうが類）　しょうが　根茎　皮なし　生', 0.9, 0.3, 6.6, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（しょうが類）　しょうが　根茎　皮なし　生　おろし', 0.7, 0.8, 16.0, 58);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（しょうが類）　しょうが　根茎　皮なし　生　おろし汁', 0.4, 0.3, 3.5, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（しょうが類）　しょうが　漬物　酢漬', 0.3, 0.2, 3.9, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（しょうが類）　しょうが　漬物　甘酢漬', 0.2, 0.4, 10.7, 44);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（しょうが類）　新しょうが　根茎　生', 0.3, 0.3, 2.7, 10);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('しろうり　果実　生', 0.9, 0.1, 3.3, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('しろうり　漬物　塩漬', 1.0, 0.1, 3.7, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('しろうり　漬物　奈良漬', 4.6, 0.2, 40.0, 216);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ずいき　生ずいき　生', 0.5, 0, 4.1, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ずいき　生ずいき　ゆで', 0.4, 0, 3.1, 10);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ずいき　干しずいき　乾', 6.6, 0.4, 63.5, 232);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ずいき　干しずいき　ゆで', 0.5, 0, 3.4, 9);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('すいぜんじな　葉　生', 0.6, 0.6, 3.4, 16);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('すぐきな　葉　生', 1.9, 0.2, 5.4, 23);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('すぐきな　根　生', 0.6, 0.1, 4.7, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('すぐきな　すぐき漬', 2.6, 0.7, 6.1, 30);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ズッキーニ　果実　生', 1.3, 0.1, 2.8, 16);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('せり　茎葉　生', 2.0, 0.1, 3.3, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('せり　茎葉　ゆで', 2.1, 0.1, 3.4, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('セロリ　葉柄　生', 0.4, 0.1, 3.6, 12);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ぜんまい　生ぜんまい　若芽　生', 1.7, 0.1, 6.6, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ぜんまい　生ぜんまい　若芽　ゆで', 1.1, 0.4, 4.1, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ぜんまい　干しぜんまい　干し若芽　乾', 14.6, 0.6, 70.8, 277);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ぜんまい　干しぜんまい　干し若芽　ゆで', 1.7, 0.1, 6.8, 25);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そらまめ　未熟豆　生', 10.9, 0.2, 15.5, 102);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('そらまめ　未熟豆　ゆで', 10.5, 0.2, 16.9, 103);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('タアサイ　葉　生', 1.3, 0.2, 2.2, 12);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('タアサイ　葉　ゆで', 1.1, 0.2, 2.3, 11);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　かいわれだいこん　芽ばえ　生', 2.1, 0.5, 3.3, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　葉だいこん　葉　生', 2.0, 0.2, 3.3, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　だいこん　葉　生', 2.2, 0.1, 5.3, 23);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　だいこん　葉　ゆで', 2.2, 0.1, 5.4, 24);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　だいこん　根　皮つき　生', 0.5, 0.1, 4.1, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　だいこん　根　皮つき　ゆで', 0.4, 0, 4.5, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　だいこん　根　皮なし　生', 0.4, 0.1, 4.1, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　だいこん　根　皮なし　生　おろし', 0.6, 0.2, 8.0, 25);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　だいこん　根　皮なし　生　おろし汁', 0.3, 0, 2.7, 12);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　だいこん　根　皮なし　生　おろし水洗い', 0.6, 0.1, 7.2, 23);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　だいこん　根　皮なし　ゆで', 0.5, 0.1, 4.0, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　切干しだいこん　乾', 9.7, 0.8, 69.7, 280);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　切干しだいこん　ゆで', 0.9, 0.1, 4.1, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　切干しだいこん　油いため', 1.5, 6.0, 7.6, 78);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　漬物　いぶりがっこ', 1.1, 0.3, 21.0, 76);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　漬物　ぬかみそ漬', 1.3, 0.1, 6.7, 29);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　漬物　たくあん漬　塩押しだいこん漬', 0.6, 0.3, 10.8, 43);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　漬物　たくあん漬　干しだいこん漬', 1.9, 0.1, 5.5, 23);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　漬物　守口漬', 5.3, 0.2, 44.3, 194);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　漬物　べったら漬', 0.4, 0.2, 13.1, 53);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　漬物　みそ漬', 2.1, 0.3, 11.4, 52);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（だいこん類）　漬物　福神漬', 2.7, 0.1, 33.3, 137);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（たいさい類）　つまみな　葉　生', 1.9, 0.3, 3.6, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（たいさい類）　たいさい　葉　生', 0.9, 0.1, 3.5, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（たいさい類）　たいさい　塩漬', 1.6, 0.1, 4.3, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('たかな　葉　生', 1.8, 0.2, 4.2, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('たかな　たかな漬', 1.9, 0.6, 6.2, 30);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('たけのこ　若茎　生', 3.6, 0.2, 4.3, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('たけのこ　若茎　ゆで', 3.5, 0.2, 5.5, 31);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('たけのこ　水煮缶詰', 2.7, 0.2, 4.0, 22);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('たけのこ　めんま　塩蔵　塩抜き', 1.0, 0.5, 3.6, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（たまねぎ類）　たまねぎ　りん茎　生', 1.0, 0.1, 8.4, 33);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（たまねぎ類）　たまねぎ　りん茎　水さらし', 0.6, 0.1, 6.1, 24);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（たまねぎ類）　たまねぎ　りん茎　ゆで', 0.8, 0.1, 7.3, 30);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（たまねぎ類）　たまねぎ　りん茎　油いため', 1.4, 5.9, 12.0, 100);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（たまねぎ類）　たまねぎ　りん茎　油いため　（あめ色たまねぎ）', 3.2, 6.8, 34.1, 208);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（たまねぎ類）　赤たまねぎ　りん茎　生', 0.9, 0.1, 9.0, 34);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（たまねぎ類）　葉たまねぎ　りん茎及び葉　生', 1.8, 0.4, 7.6, 33);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('たらのめ　若芽　生', 4.2, 0.2, 4.3, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('たらのめ　若芽　ゆで', 4.0, 0.2, 4.1, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('チコリ　若芽　生', 1.0, 0, 3.9, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ちぢみゆきな　葉　生', 3.6, 0.6, 5.7, 35);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ちぢみゆきな　葉　ゆで', 3.8, 0.7, 5.2, 34);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('チンゲンサイ　葉　生', 0.6, 0.1, 2.0, 9);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('チンゲンサイ　葉　ゆで', 0.9, 0.1, 2.4, 11);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('チンゲンサイ　葉　油いため', 0.8, 3.2, 2.2, 36);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('つくし　胞子茎　生', 3.5, 0.1, 8.1, 31);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('つくし　胞子茎　ゆで', 3.4, 0.1, 6.7, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('つるな　茎葉　生', 1.8, 0.1, 2.8, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('つるにんじん　根　生', 1.0, 0.7, 19.8, 55);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('つるむらさき　茎葉　生', 0.7, 0.2, 2.6, 11);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('つるむらさき　茎葉　ゆで', 0.9, 0.2, 3.2, 12);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('つわぶき　葉柄　生', 0.4, 0, 5.6, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('つわぶき　葉柄　ゆで', 0.3, 0, 4.4, 14);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうがらし　葉･果実　生', 3.4, 0.1, 7.2, 32);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうがらし　葉･果実　油いため', 4.0, 4.9, 8.5, 81);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうがらし　果実　生', 3.9, 3.4, 16.3, 72);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうがらし　果実　乾', 14.7, 12.0, 58.4, 270);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうがん　果実　生', 0.5, 0.1, 3.8, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とうがん　果実　ゆで', 0.6, 0.1, 3.7, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（とうもろこし類）　スイートコーン　未熟種子　生', 3.6, 1.7, 16.8, 89);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（とうもろこし類）　スイートコーン　未熟種子　ゆで', 3.5, 1.7, 18.6, 95);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（とうもろこし類）　スイートコーン　未熟種子　電子レンジ調理', 4.2, 2.2, 19.1, 104);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（とうもろこし類）　スイートコーン　未熟種子　穂軸つき　冷凍', 3.5, 1.5, 18.7, 96);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（とうもろこし類）　スイートコーン　未熟種子　カーネル　冷凍', 2.9, 1.3, 19.8, 91);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（とうもろこし類）　スイートコーン　未熟種子　カーネル　冷凍　ゆで', 2.8, 1.5, 18.7, 92);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（とうもろこし類）　スイートコーン　未熟種子　カーネル　冷凍　油いため', 2.9, 5.8, 18.9, 125);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（とうもろこし類）　スイートコーン　缶詰　クリームスタイル', 1.7, 0.5, 18.6, 82);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（とうもろこし類）　スイートコーン　缶詰　ホールカーネルスタイル', 2.3, 0.5, 17.8, 78);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（とうもろこし類）　ヤングコーン　幼雌穂　生', 2.3, 0.2, 6.0, 29);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（トマト類）　赤色トマト　果実　生', 0.7, 0.1, 4.7, 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（トマト類）　赤色ミニトマト　果実　生', 1.1, 0.1, 7.2, 30);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（トマト類）　黄色トマト　果実　生', 1.1, 0.4, 3.2, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（トマト類）　ドライトマト', 14.2, 2.1, 67.3, 291);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（トマト類）　加工品　ホール　食塩無添加', 0.9, 0.2, 4.4, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（トマト類）　加工品　トマトジュース　食塩添加', 0.7, 0.1, 4.0, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（トマト類）　加工品　トマトジュース　食塩無添加', 0.7, 0.1, 4.0, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（トマト類）　加工品　ミックスジュース　食塩添加', 0.6, 0, 4.3, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（トマト類）　加工品　ミックスジュース　食塩無添加', 0.6, 0, 4.3, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('トレビス　葉　生', 1.1, 0.2, 3.9, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('とんぶり　ゆで', 6.1, 3.5, 12.9, 89);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ながさきはくさい　葉　生', 1.3, 0.1, 2.6, 12);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ながさきはくさい　葉　ゆで', 2.2, 0.1, 3.4, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なす類）　なす　果実　生', 1.1, 0.1, 5.1, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なす類）　なす　果実　ゆで', 1.0, 0.1, 4.5, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なす類）　なす　果実　油いため', 1.5, 5.8, 6.3, 73);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なす類）　なす　果実　天ぷら', 1.6, 14.0, 12.0, 165);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なす類）　べいなす　果実　生', 1.1, 0.1, 5.3, 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なす類）　べいなす　果実　素揚げ', 1.0, 17.0, 6.7, 177);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なす類）　漬物　塩漬', 1.4, 0.1, 5.2, 22);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なす類）　漬物　ぬかみそ漬', 1.7, 0.1, 6.1, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なす類）　漬物　こうじ漬', 5.5, 0.1, 18.2, 87);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なす類）　漬物　からし漬', 2.6, 0.2, 30.7, 127);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なす類）　漬物　しば漬', 1.4, 0.2, 7.0, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('なずな　葉　生', 4.3, 0.1, 7.0, 35);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なばな類）　和種なばな　花らい・茎　生', 4.4, 0.2, 5.8, 34);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なばな類）　和種なばな　花らい・茎　ゆで', 4.7, 0.1, 4.3, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なばな類）　洋種なばな　茎葉　生', 4.1, 0.4, 6.0, 36);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（なばな類）　洋種なばな　茎葉　ゆで', 3.6, 0.4, 5.3, 30);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('にがうり　果実　生', 1.0, 0.1, 3.9, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('にがうり　果実　油いため', 1.2, 3.3, 4.6, 47);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にら類）　にら　葉　生', 1.7, 0.3, 4.0, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にら類）　にら　葉　ゆで', 2.6, 0.5, 5.7, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にら類）　にら　葉　油いため', 1.9, 5.7, 4.9, 69);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にら類）　花にら　花茎・花らい　生', 1.9, 0.2, 5.9, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にら類）　黄にら　葉　生', 2.1, 0.1, 3.3, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　葉にんじん　葉　生', 1.1, 0.2, 3.7, 16);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　皮つき　生', 0.7, 0.2, 9.3, 35);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　皮つき　ゆで', 0.6, 0.2, 8.4, 29);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　皮なし　生', 0.7, 0.2, 8.8, 32);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　皮なし　ゆで', 0.7, 0.1, 8.5, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　皮なし　油いため', 1.1, 6.4, 12.4, 103);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　皮なし　素揚げ', 1.0, 3.5, 13.9, 87);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　皮なし　カット　常法洗浄', 0.5, 0.2, 7.3, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　皮なし　カット　次亜塩素酸洗浄', 0.6, 0.2, 7.2, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　皮　生', 0.7, 0.2, 7.3, 26);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　冷凍', 0.8, 0.2, 8.2, 30);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　冷凍　ゆで', 0.7, 0.2, 7.0, 24);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　根　冷凍　油いため', 0.9, 4.0, 9.3, 65);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　グラッセ', 0.7, 1.4, 12.7, 53);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　にんじん　ジュース　缶詰', 0.6, 0.1, 6.7, 29);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　きんとき　根　皮つき　生', 1.8, 0.2, 9.6, 39);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　きんとき　根　皮つき　ゆで', 1.9, 0.2, 9.2, 37);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　きんとき　根　皮なし　生', 1.8, 0.3, 9.7, 40);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　きんとき　根　皮なし　ゆで', 1.9, 0.4, 9.6, 40);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　島にんじん　根　皮なし　生', 1.1, 0.4, 8.8, 35);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんじん類）　ミニキャロット　根　生', 0.7, 0.2, 7.5, 26);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんにく類）　にんにく　りん茎　生', 6.4, 0.9, 27.5, 129);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんにく類）　にんにく　りん茎　油いため', 8.2, 5.9, 30.6, 191);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんにく類）　茎にんにく　花茎　生', 1.9, 0.3, 10.6, 44);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（にんにく類）　茎にんにく　花茎　ゆで', 1.7, 0.2, 10.7, 43);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ねぎ類）　根深ねぎ　葉　軟白　生', 1.4, 0.1, 8.3, 35);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ねぎ類）　根深ねぎ　葉　軟白　ゆで', 1.3, 0.1, 6.8, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ねぎ類）　根深ねぎ　葉　軟白　油いため', 1.6, 4.4, 9.5, 77);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ねぎ類）　葉ねぎ　葉　生', 1.9, 0.3, 6.5, 29);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ねぎ類）　葉ねぎ　葉　油いため', 2.1, 5.2, 7.9, 77);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ねぎ類）　九条ねぎ　葉　生', 1.7, 0.3, 7.3, 32);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ねぎ類）　こねぎ　葉　生', 2.0, 0.3, 5.4, 26);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ねぎ類）　めねぎ　葉　生', 1.5, 0.3, 2.4, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('のざわな　葉　生', 0.9, 0.1, 3.5, 14);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('のざわな　漬物　塩漬', 1.2, 0.1, 4.1, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('のざわな　漬物　調味漬', 1.7, 0, 5.4, 22);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('のびる　りん茎葉　生', 3.2, 0.2, 15.5, 63);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はくさい　結球葉　生', 0.8, 0.1, 3.2, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はくさい　結球葉　ゆで', 0.9, 0.1, 2.9, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はくさい　漬物　塩漬', 1.5, 0.1, 3.3, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はくさい　漬物　キムチ', 2.3, 0.1, 5.4, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('パクチョイ　葉　生', 1.6, 0.2, 2.7, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('バジル　葉　生', 2.0, 0.6, 4.0, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('パセリ　葉　生', 4.0, 0.7, 7.8, 34);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はつかだいこん　根　生', 0.8, 0.1, 3.1, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はなっこりー　生', 3.6, 0.5, 5.4, 34);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はやとうり　果実　白色種　生', 0.6, 0.1, 4.9, 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はやとうり　果実　白色種　塩漬', 0.6, 0, 4.4, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('はやとうり　果実　緑色種　生', 0.6, 0.1, 4.9, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ビーツ　根　生', 1.6, 0.1, 9.3, 38);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ビーツ　根　ゆで', 1.5, 0.1, 10.2, 42);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ピーマン類）　青ピーマン　果実　生', 0.9, 0.2, 5.1, 20);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ピーマン類）　青ピーマン　果実　油いため', 0.9, 4.3, 5.4, 54);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ピーマン類）　赤ピーマン　果実　生', 1.0, 0.2, 7.2, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ピーマン類）　赤ピーマン　果実　油いため', 1.0, 4.3, 7.6, 69);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ピーマン類）　オレンジピーマン　果実　生', 0.9, 0.3, 4.2, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ピーマン類）　オレンジピーマン　果実　油いため', 1.1, 5.1, 7.6, 81);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ピーマン類）　黄ピーマン　果実　生', 0.8, 0.2, 6.6, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ピーマン類）　黄ピーマン　果実　油いため', 0.8, 4.3, 6.9, 61);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ピーマン類）　トマピー　果実　生', 1.0, 0.2, 7.5, 33);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ひのな　根・茎葉　生', 1.0, 0, 4.7, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ひのな　根・茎葉　甘酢漬', 1.4, 0.5, 17.3, 70);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ひろしまな　葉　生', 1.5, 0.2, 4.2, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ひろしまな　塩漬', 1.2, 0.2, 3.3, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ふき類）　ふき　葉柄　生', 0.3, 0, 3.0, 11);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ふき類）　ふき　葉柄　ゆで', 0.3, 0, 1.9, 7);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ふき類）　ふきのとう　花序　生', 2.5, 0.1, 10.0, 38);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（ふき類）　ふきのとう　花序　ゆで', 2.5, 0.1, 7.0, 31);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ふじまめ　若ざや　生', 2.5, 0.1, 7.4, 32);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ふだんそう　葉　生', 2.0, 0.1, 3.7, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ふだんそう　葉　ゆで', 2.8, 0.1, 5.4, 26);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ブロッコリー　花序　生', 5.4, 0.6, 6.6, 37);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ブロッコリー　花序　ゆで', 3.9, 0.4, 5.2, 30);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ブロッコリー　花序　電子レンジ調理', 5.7, 0.7, 7.0, 56);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ブロッコリー　花序　焼き', 9.9, 1.2, 8.4, 83);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ブロッコリー　花序　油いため', 6.9, 6.3, 6.1, 109);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ブロッコリー　芽ばえ　生', 1.9, 0.6, 2.6, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('へちま　果実　生', 0.8, 0.1, 3.8, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('へちま　果実　ゆで', 1.6, 0.1, 3.7, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ほうれんそう　葉　通年平均　生', 2.2, 0.4, 3.1, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ほうれんそう　葉　通年平均　ゆで', 2.6, 0.5, 4.0, 23);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ほうれんそう　葉　通年平均　油いため', 3.8, 8.1, 4.4, 91);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ほうれんそう　葉　夏採り　生', 2.2, 0.4, 3.1, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ほうれんそう　葉　夏採り　ゆで', 2.6, 0.5, 4.0, 23);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ほうれんそう　葉　冬採り　生', 2.2, 0.4, 3.1, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ほうれんそう　葉　冬採り　ゆで', 2.6, 0.5, 4.0, 23);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ほうれんそう　葉　冷凍', 2.9, 0.3, 3.4, 22);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ほうれんそう　葉　冷凍　ゆで', 3.7, 0.5, 3.8, 26);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ほうれんそう　葉　冷凍　油いため', 4.0, 4.5, 5.4, 67);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ホースラディシュ　根茎　生', 3.1, 0.3, 17.7, 69);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('まこも　茎　生', 1.3, 0.2, 4.4, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('みずかけな　葉　生', 2.9, 0.1, 4.7, 25);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('みずかけな　塩漬', 4.9, 0, 5.7, 34);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('みずな　葉　生', 2.2, 0.1, 4.8, 23);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('みずな　葉　ゆで', 2.0, 0.1, 4.7, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('みずな　塩漬', 2.0, 0.1, 5.9, 26);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（みつば類）　切りみつば　葉　生', 1.0, 0.1, 4.0, 16);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（みつば類）　切りみつば　葉　ゆで', 0.9, 0.1, 3.3, 12);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（みつば類）　根みつば　葉　生', 1.9, 0.1, 4.1, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（みつば類）　根みつば　葉　ゆで', 2.3, 0.1, 3.9, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（みつば類）　糸みつば　葉　生', 0.9, 0.1, 2.9, 12);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（みつば類）　糸みつば　葉　ゆで', 1.1, 0, 4.0, 14);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('みぶな　葉　生', 1.1, 0.3, 2.9, 14);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（みょうが類）　みょうが　花穂　生', 0.9, 0.1, 2.6, 11);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（みょうが類）　みょうがたけ　茎葉　生', 0.4, 0.1, 1.5, 6);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('むかご　肉芽　生', 2.9, 0.2, 20.6, 87);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('めキャベツ　結球葉　生', 5.7, 0.1, 9.9, 52);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('めキャベツ　結球葉　ゆで', 5.3, 0.1, 9.8, 51);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('めたで　芽ばえ　生', 3.0, 0.5, 8.8, 39);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（もやし類）　アルファルファもやし　生', 1.6, 0.1, 2.0, 11);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（もやし類）　だいずもやし　生', 3.6, 1.4, 2.5, 29);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（もやし類）　だいずもやし　ゆで', 2.9, 1.6, 2.2, 27);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（もやし類）　だいずもやし　油いため', 3.8, 4.5, 4.1, 62);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（もやし類）　ブラックマッペもやし　生', 2.2, 0, 2.8, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（もやし類）　ブラックマッペもやし　ゆで', 1.3, 0, 2.7, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（もやし類）　ブラックマッペもやし　油いため', 2.3, 0.9, 5.8, 41);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（もやし類）　りょくとうもやし　生', 1.8, 0.1, 2.4, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（もやし類）　りょくとうもやし　ゆで', 1.6, 0, 2.3, 12);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（もやし類）　りょくとうもやし　油いため', 2, 2.8, 4, 40);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('モロヘイヤ　茎葉　生', 4.8, 0.5, 6.3, 36);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('モロヘイヤ　茎葉　ゆで', 3.0, 0.4, 4.0, 24);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('やぶまめ　生', 15.5, 6.5, 29.5, 219);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('やまごぼう　みそ漬', 4.1, 0.1, 15.6, 66);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ゆりね　りん茎　生', 3.8, 0.1, 28.3, 119);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ゆりね　りん茎　ゆで', 3.4, 0.1, 28.7, 117);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ようさい　茎葉　生', 2.2, 0.1, 3.1, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ようさい　茎葉　ゆで', 2.2, 0.1, 4.1, 18);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('よめな　葉　生', 3.4, 0.2, 10.0, 40);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('よもぎ　葉　生', 5.2, 0.3, 8.7, 43);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('よもぎ　葉　ゆで', 4.8, 0.1, 8.2, 37);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('らっかせい　未熟豆　生', 12.0, 24.2, 12.4, 306);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('らっかせい　未熟豆　ゆで', 11.9, 23.5, 12.3, 298);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（らっきょう類）　らっきょう　りん茎　生', 1.4, 0.2, 29.3, 83);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（らっきょう類）　らっきょう　甘酢漬', 0.4, 0.3, 29.4, 117);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（らっきょう類）　エシャレット　りん茎　生', 2.3, 0.2, 17.8, 59);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('リーキ　りん茎葉　生', 1.6, 0.1, 6.9, 30);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('リーキ　りん茎葉　ゆで', 1.3, 0.1, 6.8, 28);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ルッコラ　葉　生', 1.9, 0.4, 3.1, 17);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ルバーブ　葉柄　生', 0.7, 0.1, 6.0, 23);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('ルバーブ　葉柄　ゆで', 0.5, 0.1, 4.6, 14);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（レタス類）　レタス　土耕栽培　結球葉　生', 0.6, 0.1, 2.8, 11);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（レタス類）　レタス　水耕栽培　結球葉　生', 0.8, 0.2, 2.9, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（レタス類）　サラダな　葉　生', 1.0, 0.2, 2.7, 10);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（レタス類）　リーフレタス　葉　生', 1.4, 0.1, 3.3, 16);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（レタス類）　サニーレタス　葉　生', 1.2, 0.2, 3.2, 15);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（レタス類）　サンチュ　葉　生', 1.2, 0.4, 2.5, 14);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（レタス類）　コスレタス　葉　生', 1.2, 0.2, 3.4, 16);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('れんこん　根茎　生', 1.9, 0.1, 15.5, 66);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('れんこん　根茎　ゆで', 1.3, 0.1, 16.1, 66);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('れんこん　甘酢れんこん', 0.6, 0.2, 16.5, 66);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('わけぎ　葉　生', 1.6, 0, 7.4, 30);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('わけぎ　葉　ゆで', 1.9, 0, 6.9, 29);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('わさび　根茎　生', 5.6, 0.2, 18.4, 89);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('わさび　わさび漬', 7.1, 0.5, 28.0, 140);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('わらび　生わらび　生', 2.4, 0.1, 4.0, 19);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('わらび　生わらび　ゆで', 1.5, 0.1, 3.0, 13);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('わらび　干しわらび　乾', 20.0, 0.7, 61.4, 216);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（その他）　ミックスベジタブル　冷凍', 3.0, 0.7, 15.1, 67);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（その他）　ミックスベジタブル　冷凍　ゆで', 3.1, 0.8, 14.6, 65);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（その他）　ミックスベジタブル　冷凍　油いため', 3.3, 4.9, 15.7, 108);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（その他）　野菜ミックスジュース　通常タイプ', 0.8, 0.1, 4.7, 21);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('（その他）　野菜ミックスジュース　濃縮タイプ', 1.0, 0.3, 7.8, 36);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あけび　果肉　生', 0.5, 0.1, 22.0, 89);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あけび　果皮　生', 0.3, 0.3, 8.6, 32);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アサイー　冷凍　無糖', 0.9, 5.3, 5.0, 62);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アセロラ　酸味種　生', 0.7, 0.1, 9.0, 36);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アセロラ　甘味種　生', 0.7, 0.1, 9.0, 36);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アセロラ　果実飲料　10%果汁入り飲料', 0.1, 0, 10.5, 42);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アテモヤ　生', 1.8, 0.4, 19.4, 81);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('アボカド　生', 2.1, 17.5, 7.9, 176);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あんず　生', 1.0, 0.3, 8.5, 37);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あんず　乾', 9.2, 0.4, 70.4, 296);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あんず　缶詰', 0.5, 0.4, 18.9, 79);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あんず　ジャム　高糖度', 0.3, 0.1, 64.9, 252);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('あんず　ジャム　低糖度', 0.4, 0.1, 50.5, 202);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いちご　生', 0.9, 0.1, 8.5, 31);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いちご　ジャム　高糖度', 0.4, 0.1, 63.3, 250);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いちご　ジャム　低糖度', 0.5, 0.1, 48.4, 194);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いちご　乾', 0.5, 0.2, 82.8, 329);
INSERT INTO foods(name, protein, fat, carbs, calories) VALUES ('いちじく　生', 0.6, 0.1, 14.3, 57);