spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/dev
    baseline-version: 0
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

security:
  jwt:
    token:
      secretkey: ${JWT_SECRETKEY}
      expirationMs: ${JWT_EXPIRATIONTIME}
