spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwt:
    token:
      secretkey: ${JWT_SECRETKEY}
      expirationMs: ${JWT_EXPIRATIONTIME}
