spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    locations: classpath:db/migrations
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

logging:
  level:
    db:
      migration: DEBUG

security:
  jwt:
    token:
      secretkey: AbSkLRzZ6QQlJUEGoBCrm+Y/UZgjbqVtRdZwHYNDqT1N8WOaoq61QTsdpQw+78+n/O4FoRol44Imp9TTYhxPxQ==
      expirationMs: 3000000
